### ISSUE TITLE
Can't build for Linux (on MacOS and Linux)

### ISSUE THREAD

**Issue by danielmarkow** [pganalyze/pg_query_go#137]
Base system:
Macbook Pro M1 Max
MacOS 15.4.1 (24E263)
Go version 1.24.2

minimum reproduceable example
```go
package main

import (
	"fmt"

	pg_query "github.com/pganalyze/pg_query_go/v6"
)

func main() {
	result, err := pg_query.Parse("SELECT 42")
	if err != nil {
		panic(err)
	}

	// This will output "42"
	fmt.Printf("%d\n", result.Stmts[0].Stmt.GetSelectStmt().GetTargetList()[0].GetResTarget().GetVal().GetAConst().GetIval().Ival)
}
```

building for mac works without error
```bash
go build .
```

building for linux using 
```bash
export GOOS=linux
export GOARCH=arm64
go build .
```

results in an error
```
./main.go:10:26: undefined: pg_query.Parse
```

edit:
tried it in a container golang:1.24.2-alpine3.21 as well, same error :/

**Comment by danielmarkow** [comment]
It works in the golang:1.24.3-bookworm container. I assume because gcc is installed.

**Comment by danielmarkow** [comment]
I wish the error message would be clearer but thats a cgo thing...
